{% set version = '1.8' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pdftools
  version: {{ version|replace("-", "_") }}

source:
  fn: pdftools_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/pdftools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pdftools/pdftools_{{ version }}.tar.gz
  sha256: 5f790c3678eacdc15147a671571c86b5f8d6eb692fa680324bc5d27542e6d0fb

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}automake          # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}sed  # [win]
    - {{posix}}coreutils  # [win]

  host:
    - r-base
    - r-rcpp >=0.12.12
    - poppler

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.12.12

test:
  commands:
    - $R -e "library('pdftools')"           # [not win]
    - "\"%R%\" -e \"library('pdftools')\""  # [win]

about:
  home: https://ropensci.org/blog/2016/03/01/pdftools-and-jeroen (blog) https://github.com/ropensci/pdftools#readme
    (devel) https://poppler.freedesktop.org (upstream)
  license: MIT
  summary: Utilities based on 'libpoppler' for extracting text, fonts, attachments and  metadata
    from a PDF file. Also supports high quality rendering of PDF documents info PNG,
    JPEG, TIFF format, or into raw bitmap vectors for further processing in R.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - stevierene82
